services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: titine
      POSTGRES_PASSWORD: titine
      POSTGRES_DB: titine
    ports:
      - '5435:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
